In [1]:
import warnings
warnings.filterwarnings(action='ignore')
from functools import partial
from shapely import ops
import pyproj
import json, math
import matplotlib.pyplot as plt
from folium import plugins
import re
from matplotlib import font_manager, rc, rcParams
# def set_korea_font():
#     font_name = font_manager.FontProperties(fname="/System/Library/Fonts/Supplemental/AppleGothic.ttf").get_name()
#     rc('font', family=font_name)
#     rcParams.update({'font.size': 11})
#     rcParams['axes.unicode_minus'] = False  
# set_korea_font()
from shapely.geometry import Point as shapely_Point
from geopy.distance import great_circle as distance
from geopy.point import Point as Point
from math import sin, cos, atan2, sqrt, degrees, radians, pi

from geopy.distance import geodesic
import folium
from folium import plugins
import geopandas as gpd
import numpy as np
import pandas as pd
import shapely
import os
import datetime

#reproject import 필요

os.chdir('./data')

def reproject(geom, from_proj=None, to_proj=None):
    tfm = partial(pyproj.transform, pyproj.Proj(init=from_proj), pyproj.Proj(init=to_proj))
    return ops.transform(tfm, geom)

In [5]:
df1 = pd.concat([pd.read_csv('0_1500.csv'), pd.read_csv('1500_2214.csv'), pd.read_csv('2214_4428.csv'), pd.read_csv('4428_6642.csv'), pd.read_csv('6642_8856.csv')])
df1.index = range(len(df1))
df1.to_csv("0_8856.csv", index = False)

In [6]:
pd.read_csv("0_8856.csv")

,lon,lat,overspeed_cam_count100,floating_pop_count50,bump_count0,parking_count12.5,parking_count25,car_count1000,child_count1000,elem_kinder_count400,...,chaos1_nearby_count25,chaos1_nearby_count50,width_nearby_count12.5,width_nearby_count25,cross_road_nearby_count12.5,cross_road_nearby_count25,num_cram_school_count400,shortest_cross_count0,shortest_traffic_signal_count0,shortest_sidewalk_count0
0,127.061509,37.149281,0,390.898125,143.582568,0,0,470,24.0,1,...,69.890000,84.572500,1.0,1.333333,2,3,17,0.000000,4.965855,58.860463
1,127.061615,37.149503,0,507.739167,117.121977,0,0,470,24.0,1,...,79.786667,82.809375,1.0,1.750000,1,4,17,19.934105,16.786558,42.782539
2,127.061865,37.149617,0,364.718889,98.525988,0,0,470,24.0,1,...,94.676667,79.335000,1.0,2.000000,2,3,26,16.631819,21.477201,33.348896
3,127.060957,37.149433,0,427.077917,154.755132,0,0,470,24.0,1,...,96.023750,88.858333,1.0,2.000000,1,3,4,11.360300,9.200259,8.918163
4,127.061237,37.149457,0,476.310556,137.437890,0,0,470,24.0,1,...,79.570000,90.390000,1.0,2.000000,1,3,17,24.794651,27.730343,29.463053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8851,127.060176,37.169517,0,65.023333,111.916284,0,0,1576,193.0,4,...,98.180000,80.493000,1.0,1.500000,0,0,21,73.965878,77.898523,28.913754
8852,127.060430,37.169633,0,69.116944,137.322563,0,0,1576,193.0,4,...,100.000000,72.146667,1.0,1.000000,0,0,21,54.106111,58.622619,31.394445
8853,127.060416,37.169753,0,30.628750,141.076523,0,0,1576,193.0,4,...,100.000000,100.000000,1.0,1.000000,0,0,21,60.725272,60.348157,44.209104
8854,127.060214,37.169860,0,63.999583,130.845389,0,0,1576,193.0,4,...,100.000000,85.557500,1.0,1.000000,0,0,21,67.094765,65.222149,40.431478
8855,127.059933,37.169816,0,51.494444,107.579160,0,0,1576,193.0,6,...,98.180000,97.258750,1.0,1.500000,0,0,21,79.573648,84.962419,39.760944